import kmapper as km
import dyneusr as dsr
import pandas as pd
import numpy as np
import matplotlib.cm as cm
import os

class TDAVisualizer():
    '''
    Class for visualizing a topological graph using either KeplerMapper or DyNeuSR.
    '''
    def __init__(self,
                 graph,
                 path_html: str,
                 output_path: str = None):
        super().__init__()
        '''
        Initialize the TDAVisualizer object.

        Parameters:
        - graph: Topological graph generated by KeplerMapper
        - path_html: Filename for the HTML output
        - output_path: Directory path for saving the HTML file
        '''
        self.graph = graph

        self.path_html = path_html
        self.output_path = output_path

        self.mapper = km.KeplerMapper(verbose=0)

    def visualize(self, type_: str, target = None, template: str = '4D'):
        '''
        Visualize the graph in an interactive format.
        
        Parameters:
        - type_: Visualization type. Options:
            - 'kepler': KeplerMapper visualization
            - 'dyn': DyNeuSR visualization
        - target: Optional labels to be passed to DyNeuSR for coloring
        '''
        if type_ == 'dyn':
            dyneugraph = dsr.DyNeuGraph(G=self.graph, y=target)
            dyneugraph.visualize(self.output_path + '/' + self.path_html, show=False, template=template)
        elif type_ == 'kepler':
            self.mapper.visualize(graph=self.graph, path_html=self.output_path + self.path_html)

    def visualize_with_communities(self, 
                                   communities: list,
                                   color_col: str = 'community',
                                   template: str = '4D'):
        save_path = os.path.join(self.output_path, self.path_html)

        node_to_comm = {}
        for comm_id, comm_nodes in enumerate(communities):
            for node in comm_nodes:
                node_to_comm[node] = comm_id

        node_info = pd.DataFrame.from_dict(
            node_to_comm, orient='index', columns=[color_col]
        )
        node_info.index.name = 'id'

        node_info_one_hot = pd.get_dummies(node_info[color_col], prefix=color_col)
        node_info_one_hot.index = node_info.index
        node_info_one_hot = node_info_one_hot.astype(int)

        dyneugraph = dsr.DyNeuGraph(G=self.graph, y=node_info)
        dyneugraph.visualize(save_path, show=False, template=template)

        return node_info